### PR TITLE
Fixed physics library load issue

### PR DESCRIPTION
**Pull request by crbozz**
Also added x86 and x86_64 bullet binaries.

SXR-DCO-1.0-Signed-off-by: Cristiano Bozzetto [c.bozzetto@samsung.com](mailto:c.bozzetto@samsung.com)

### CODE REVIEW

**Comment by liaxim** [comment]
Needs SXR DCO.

**Comment by liaxim** [comment]
Works. Thanks.

**Comment by liaxim** [comment]
@crbozz Can you please add the DCO so we can merge? Thanks

**Comment by crbozz** [comment]
I hope I did it right!

**Pull request merged**
