### PR TITLE
Blending animationsv2

### PR DESCRIPTION
**Pull request by spodila1**
Added support for blending animations.

This PR is based on PR #105 where changes are made to simplify repetitive code. 

As SXRAvatar was getting complicated the animation sequencing is made to be a separate class (SXRAnimationQueue) and it handles everything related to blending between animations.

Tested with all the sxrsdk-demos, modified and made a PR on repo sxrsdk-demos https://github.com/sxrsdk/sxrsdk-demos/pull/75

SXR DCO signed off by: Sahithi Podila sah.pod@partner.samsung.com

### CODE REVIEW

**Comment by liaxim** [comment]
Can we close https://github.com/sxrsdk/sxrsdk/pull/105 then?

Merge conflict is shown:
```
Conflicting files
`.travis.yml`
`SXR/SDK/sxrsdk/src/main/java/com/samsungxr/animation/SXRAvatar.java`
```

**Comment by spodila1** [comment]
@liaxim Yes you can close #105

**Comment by liaxim** [comment]
Still shows a conflict:
```
Conflicting files
SXR/SDK/sxrsdk/src/main/java/com/samsungxr/animation/SXRAvatar.java
```

**Comment by NolaDonato** [comment]
All the demos work, this can be merged

**Comment by liaxim** [comment]
sxr-multilight: the astroboy is not visible. Used both this and the corresponding demos PR, cleaned&rebuilt couple of times.

**Comment by liaxim** [comment]
sxr-morph: no animation
sxr-rendertotexture: astroboy missing

**Comment by spodila1** [comment]
> sxr-morph: no animation
> sxr-rendertotexture: astroboy missing

I have fixed these. Made changes both in demos and sdk

**Pull request merged**
