### PR TITLE
JAV8 modules updated

### PR DESCRIPTION
**Pull request by xcaostagit**
Now includes x86 and x86_64 ABIs

SXR-DCO-1.0-Signed-off-by: Xu Cao xu.c@samsung.com

### CODE REVIEW

**Comment by liaxim** [comment]
Have you tried the x86 binaries in the emulator?

**Comment by liaxim** [comment]
Needs SXR DCO.

**Comment by liaxim** [comment]
@xcaostagit Can you please add the DCO so we can merge? Thanks

**Comment by xcaostagit** [comment]
@liaxim Please review. There seems to be no way for github to accept comment-only changes and I had to add the DCO to the commit. So I added a dummy entry to .gitignore in order for the DCO to appear in this change. Let me know if you disagree with this approach.

**Comment by liaxim** [comment]
You just have to add the SXR-DCO to the pull request.

**Pull request merged**
