### PR TITLE
Fix GLB chunk parsing

### PR DESCRIPTION
**Pull request by NolaDonato**
We are getting GLB files without the correct padding between chunks. This PR had updated assimp binaries with the fix. No changes to SXR code, just libraries.

SXR DCO signed off by: Nola Donato nola.donato@samsung.com

### CODE REVIEW

**Comment by liaxim** [comment]
Something is wrong with the binaries; see the travis build log:

```
  [x86] SharedLibrary  : libsxrsdk.so
  /home/travis/build/sxrsdk/sxrsdk/android-ndk-r18b/toolchains/x86-4.9/prebuilt/linux-x86_64/lib/gcc/i686-linux-android/4.9.x/../../../../i686-linux-android/bin/ld: error: /home/travis/build/sxrsdk/sxrsdk/SXR/SDK/sxrsdk/build/intermediates/ndkBuild/debug/obj/local/x86/libassimp.so: incompatible target
  /home/travis/build/sxrsdk/sxrsdk/SXR/SDK/sxrsdk/src/main/jni/contrib/jassimp/jassimp.cpp:2076: error: undefined reference to 'Assimp::Importer::Importer()'
  /home/travis/build/sxrsdk/sxrsdk/SXR/SDK/sxrsdk/src/main/jni/contrib/jassimp/jassimp.cpp:2081: error: undefined reference to 'Assimp::Intern::AllocateFromAssimpHeap::operator new(unsigned int)'
  /home/travis/build/sxrsdk/sxrsdk/SXR/SDK/sxrsdk/src/main/jni/contrib/jassimp/jassimp.cpp:2081: error: undefined reference to 'Assimp::Importer::SetIOHandler(Assimp::IOSystem*)'
  /home/travis/build/sxrsdk/sxrsdk/SXR/SDK/sxrsdk/src/main/jni/contrib/jassimp/jassimp.cpp:2081: error: undefined reference to 'Assimp::Intern::AllocateFromAssimpHeap::operator delete(void*)'
  /home/travis/build/sxrsdk/sxrsdk/SXR/SDK/sxrsdk/src/main/jni/contrib/jassimp/jassimp.cpp:2088: error: undefined reference to 'Assimp::Importer::ReadFile(char const*, unsigned int)'
  /home/travis/build/sxrsdk/sxrsdk/SXR/SDK/sxrsdk/src/main/jni/contrib/jassimp/jassimp.cpp:2148: error: undefined reference to 'Assimp::Importer::GetErrorString() const'
  /home/travis/build/sxrsdk/sxrsdk/SXR/SDK/sxrsdk/src/main/jni/contrib/jassimp/jassimp.cpp:2162: error: undefined reference to 'Assimp::Importer::~Importer()'
  /home/travis/build/sxrsdk/sxrsdk/SXR/SDK/sxrsdk/src/main/jni/contrib/jassimp/jassimp.cpp:2162: error: undefined reference to 'Assimp::Importer::~Importer()'
  /home/travis/build/sxrsdk/sxrsdk/SXR/SDK/sxrsdk/src/main/jni/contrib/assimp/include/assimp/Importer.hpp:217: error: undefined reference to 'Assimp::Importer::SetPropertyInteger(char const*, int)'
  /home/travis/build/sxrsdk/sxrsdk/SXR/SDK/sxrsdk/src/main/jni/contrib/jassimp/jassimp.cpp:554: error: undefined reference to 'Assimp::Intern::AllocateFromAssimpHeap::operator delete(void*)'
  /home/travis/build/sxrsdk/sxrsdk/SXR/SDK/sxrsdk/src/main/jni/contrib/jassimp/jassimp.cpp:601: error: undefined reference to 'Assimp::Intern::AllocateFromAssimpHeap::operator new(unsigned int)'
  /home/travis/build/sxrsdk/sxrsdk/SXR/SDK/sxrsdk/src/main/jni/contrib/jassimp/jassimp.cpp:601: error: undefined reference to 'Assimp::Intern::AllocateFromAssimpHeap::operator delete(void*)'
  /home/travis/build/sxrsdk/sxrsdk/SXR/SDK/sxrsdk/src/main/jni/contrib/jassimp/jassimp.cpp:490: error: undefined reference to 'Assimp::Intern::AllocateFromAssimpHeap::operator delete(void*)'
  /home/travis/build/sxrsdk/sxrsdk/SXR/SDK/sxrsdk/src/main/jni/contrib/assimp/include/assimp/material.inl:81: error: undefined reference to 'aiGetMaterialTextureCount'
  /home/travis/build/sxrsdk/sxrsdk/SXR/SDK/sxrsdk/build/intermediates/ndkBuild/debug/obj/local/x86/objs-debug/sxrsdk/contrib/jassimp/jassimp.o:jassimp.cpp:vtable for Assimp::IOSystem: error: undefined reference to 'Assimp::IOSystem::ComparePaths(char const*, char const*) const'
  /home/travis/build/sxrsdk/sxrsdk/SXR/SDK/sxrsdk/build/intermediates/ndkBuild/debug/obj/local/x86/objs-debug/sxrsdk/contrib/jassimp/jassimp.o:jassimp.cpp:vtable for JavaIOSystem: error: undefined reference to 'Assimp::IOSystem::ComparePaths(char const*, char const*) const'
  /home/travis/build/sxrsdk/sxrsdk/SXR/SDK/sxrsdk/src/main/jni/engine/exporter/exporter.cpp:41: error: undefined reference to 'Assimp::Exporter::GetExportFormatCount() const'
  /home/travis/build/sxrsdk/sxrsdk/SXR/SDK/sxrsdk/src/main/jni/engine/exporter/exporter.cpp:49: error: undefined reference to 'Assimp::Exporter::GetExportFormatCount() const'
  /home/travis/build/sxrsdk/sxrsdk/SXR/SDK/sxrsdk/src/main/jni/engine/exporter/exporter.cpp:50: error: undefined reference to 'Assimp::Exporter::GetExportFormatDescription(unsigned int) const'
  /home/travis/build/sxrsdk/sxrsdk/SXR/SDK/sxrsdk/src/main/jni/engine/exporter/exporter.cpp:51: error: undefined reference to 'Assimp::Exporter::GetExportFormatDescription(unsigned int) const'
  /home/travis/build/sxrsdk/sxrsdk/SXR/SDK/sxrsdk/src/main/jni/engine/exporter/exporter.cpp:54: error: undefined reference to 'Assimp::Exporter::GetExportFormatDescription(unsigned int) const'
  /home/travis/build/sxrsdk/sxrsdk/SXR/SDK/sxrsdk/src/main/jni/engine/exporter/exporter.cpp:119: error: undefined reference to 'aiNode::aiNode()'
  /home/travis/build/sxrsdk/sxrsdk/SXR/SDK/sxrsdk/src/main/jni/engine/exporter/exporter.cpp:123: error: undefined reference to 'aiMaterial::aiMaterial()'
  /home/travis/build/sxrsdk/sxrsdk/SXR/SDK/sxrsdk/src/main/jni/engine/exporter/exporter.cpp:142: error: undefined reference to 'aiNode::aiNode()'
  /home/travis/build/sxrsdk/sxrsdk/SXR/SDK/sxrsdk/src/main/jni/engine/exporter/exporter.cpp:170: error: undefined reference to 'Assimp::Exporter::Exporter()'
  /home/travis/build/sxrsdk/sxrsdk/SXR/SDK/sxrsdk/src/main/jni/engine/exporter/exporter.cpp:178: error: undefined reference to 'aiScene::aiScene()'
  /home/travis/build/sxrsdk/sxrsdk/SXR/SDK/sxrsdk/src/main/jni/engine/exporter/exporter.cpp:188: error: undefined reference to 'aiScene::~aiScene()'
  /home/travis/build/sxrsdk/sxrsdk/SXR/SDK/sxrsdk/src/main/jni/engine/exporter/exporter.cpp:188: error: undefined reference to 'aiScene::~aiScene()'
  /home/travis/build/sxrsdk/sxrsdk/SXR/SDK/sxrsdk/src/main/jni/engine/exporter/exporter.cpp:188: error: undefined reference to 'Assimp::Exporter::~Exporter()'
  /home/travis/build/sxrsdk/sxrsdk/SXR/SDK/sxrsdk/src/main/jni/engine/exporter/exporter.cpp:188: error: undefined reference to 'Assimp::Exporter::~Exporter()'
  /home/travis/build/sxrsdk/sxrsdk/SXR/SDK/sxrsdk/src/main/jni/contrib/assimp/include/assimp/Exporter.hpp:477: error: undefined reference to 'Assimp::Exporter::Export(aiScene const*, char const*, char const*, unsigned int, Assimp::ExportProperties const*)'
  clang++: error: linker command failed with exit code 1 (use -v to see invocation)
  make: *** [/home/travis/build/sxrsdk/sxrsdk/SXR/SDK/sxrsdk/build/intermediates/ndkBuild/debug/obj/local/x86/libsxrsdk.so] Error 1
```

**Comment by NolaDonato** [comment]
I have pushed a fix for the x86 lib

**Comment by liaxim** [comment]
Still failing due to undefined references to Assimp

**Comment by liaxim** [comment]
I believe Xu did the previous x86 binaries.

**Comment by xcaostagit** [comment]
The following symbols exist in ./SXR/SDK/sxrsdk/src/main/prebuilt/x86_64/libassimp.so (from "nm -D" dump):

00000000001a71e0 T Assimp::Exporter::ExportToBlob(aiScene const*, char const*, unsigned int, Assimp::ExportProperties const*)
00000000001a70e0 T Assimp::Exporter::SetIOHandler(Assimp::IOSystem*)
00000000001a82b0 T Assimp::Exporter::RegisterExporter(Assimp::Exporter::ExportFormatEntry const&)
00000000001a8460 T Assimp::Exporter::UnregisterExporter(char const*)
00000000001a74e0 T Assimp::Exporter::Export(aiScene const*, char const*, char const*, unsigned int, Assimp::ExportProperties const*)
00000000001a6fb0 T Assimp::Exporter::FreeBlob()
00000000001a6d50 T Assimp::Exporter::Exporter()
00000000001a6d50 T Assimp::Exporter::Exporter()
00000000001a6f40 T Assimp::Exporter::~Exporter()
00000000001a6f40 T Assimp::Exporter::~Exporter()

I will look deeper into this issue and update later

**Comment by xcaostagit** [comment]
OK after a deeper look into the issue... @NolaDonato you can take my entire build environment and compare it with yours; or you can give me your changes to the sources so I can make the build for you - whichever is convenient for you.

**Comment by NolaDonato** [comment]
I tried again, sxrsdk built for me on Windows on all 4 platforms

**Comment by liaxim** [comment]
Still fails. Tried it locally too. The binary checked in as x86 is not x86;

```
$ file ./sxrsdk/src/main/prebuilt/x86/libassimp.so
./sxrsdk/src/main/prebuilt/x86/libassimp.so: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=ca57c92af4738341374545a5336c0b77ba2e29b1, stripped
```

**Comment by xcaostagit** [comment]
I can build sxrsdk successfully with the updated binaries.

**Pull request merged**
