### PR TITLE
Blending animationsv1

### PR DESCRIPTION
**Pull request by spodila1**
Blending is added among skeleton animations for SXRRepeatMode._ONCE_, SXRRepeatMode._PINGPONG_, SXRRepeatMode._REPEATED_.
   
1. Modified SXRAvatar to support _PINGPONG_ mode.

2. Added couple of methods start(blendFactor), reverseAnimations(), setStartParameters(),  onFinish(), removeBlendAnimation(), setAvatar() to SXRAnimator 

3. Added support for blending skeleton animations to SXRPoseInterpolator.

4. Changed the variable name animationOffset to mAnimationOffset in SXRPoseMapper.

5. Added methods setSkelAnimOrder(), setUpdatePose() and getSkelAnimOrder methods to SXRSkeletonAnimation.

6. Changed the variable names from animationOffset, animationSpeed to mAnimationOffset , mAnimationSpeed respectively. Added methods setReverse(), setID(), setBlend(), getID(), getAnimation(), setPlayAnimation(), updateAnimation() and modified onDrawFrame() in SXRAnimation.

     

Tested with sxr-avatar demo  (PR #65)

SXR DCO signed off by: Sahithi Podila sah.pod@partner.samsung.com

### CODE REVIEW

**Comment by NolaDonato** [comment]
Please explain the hardcoded stuff you put in SXRAnimation.onDrawFrame

**Comment by spodila1** [comment]
Changed the structure of adding blend animations.

1. Modified SXRAvatar to support PINGPONG and REPEATED mode. Blending happens here in SXRAvatar between animators. Added methods addBlendAnimation(int index, float duration, int position), playDummyAnimation(SXRAnimator animator), addPoseAnimation(SXRAnimator animator, float duration, int position), orderAnimations(), reverseAnimations() and setRepeatModeAndCount()

2. Added SXRAnimationOrder which assigns name to animations in sequence. 

3. Added setReverse(boolean reverse) and setBlend(boolean blend, float blendDuration) methods to SXRAnimation and SXRAnimator.

**Comment by dsazulay** [comment]
Hi @spodila1, how can I build this branch? I am getting this error when I try to build: https://travis-ci.com/sxrsdk/sxrsdk/builds/98688151#L2247

**Comment by spodila1** [comment]
@dsazulay  Can you build now. I have fixed the error.

**Comment by dsazulay** [comment]
It worked. Thanks!

**Comment by NolaDonato** [comment]
I have reviewed your changes and have some ideas:
1. It is not a good idea to complicate commonly used classes like SXRAnimation with extra features like blending that are specific to a use case (sequencing). I do not see any benefit to handling blending in SXRAnimator.
2. SXRAvatar was getting complicated and the animation sequencing is general enough that it could be used independently. The animation sequencing should be a separate class and it should handle everything related to blending between animations.
3. You duplicated a lot of code to run thru skeletal animations and compute poses in SXRPoseInterpolator. All this class has to do is interpolate between two poses - it does not have to actually animate the poses.

I realize my comments are vague and this is a complex task. I made a pull request against your repo with the changes I have suggested. Please review them and give me your feedback. I think this will make the blend tree thing a lot simpler.

**Comment by liaxim** [comment]
#### Conflicting files
`SXR/SDK/sxrsdk/src/main/java/com/samsungxr/animation/SXRAvatar.java`

**Pull request closed without merging**
