### PR TITLE
first crack at travis integration

### PR DESCRIPTION
**Pull request by thomasflynn**
first crack at travis integration

SXR-DCO-Signed-off-by: Tom Flynn
tom.flynn@samsung.com

### CODE REVIEW

**Comment by thomasflynn** [comment]
don't merge yet.  if this succeeds in building, i have one more commit to make sure it builds the extensions.

**Comment by thomasflynn** [comment]
looks like my commit for the extensions worked.  this can be merged now.

**Comment by liaxim** [comment]
Fyi:
android-ndk-r13b is quite old
only_monoscopic didn't affect the framework build in the past, only the demos; now it is obsolete, the demos have build variants instead

**Comment by thomasflynn** [comment]
yeah, i was conservative on the ndk.  that is the version that was used in the GearVRf-Demos build.  what version do you recommend?

only_monoscopic did seem to affect the framework build because without it, it was complaining about the Oculus SDK.

**Comment by liaxim** [comment]
Yep, I was wrong about only_monoscopic. It is only there for the sdk build.

Any ndk after v16 should be good.

**Pull request merged**
