### PR TITLE
libjav8.so updates

### PR DESCRIPTION
**Pull request by xcaostagit**
The current version of libjav8.so was built with NDK 16b. It is reported to crash
when used in sxr-x3ddemo on armeabi. I spent much time investigating this issue
however I cannot explain why this crash shall occur.

These updated binaries are produced in the same build with NDK 15c. The armeabi
version has been verified to work with sxr-x3ddemo.

### CODE REVIEW

**Comment by liaxim** [comment]
Works for me.

.

**Comment by liaxim** [comment]
I think in NDK16 the standard C++ library has some symbols exported that are not by other NDKs

**Comment by xcaostagit** [comment]
Thanks @liaxim It's interesting those "problem" binaries used to work in GearVRf but not now in sxrsdk.

**Comment by liaxim** [comment]
Might be depending on the version of the NDK we use for the SDK.

**Pull request merged**
