### PR TITLE
add SXRStateMachine, add SXRAnimation.copy

### PR DESCRIPTION
**Pull request by NolaDonato**
1. Added the ability to clone animations so that the same animation can be in the queue more than once with different properties
2. Add SXRStateMachine and SXRAnimationStateMachine to supply a finite state machine for application logic. Can start and stop animations under state machine control.

This feature has been tested in the dressup app but there aren't any unit tests for it yet.

SXR DCO signed off by: Nola Donato nola.donato@samsung.com

### CODE REVIEW

**Comment by NolaDonato** [comment]
this has been rebased today

**Comment by thomasflynn** [comment]
this now has conflicts

**Comment by NolaDonato** [comment]
i rebased the wrong branch before, thats why it still had conflicts

**Comment by thomasflynn** [comment]
ok, with the MixedReality buildfix merged in, this builds now.  gonna merge.

**Pull request merged**
