### PR TITLE
Abstract body tracking API

### PR DESCRIPTION
**Pull request by liaxim**
Add GVRBodyTracker to provide an abstract body tracking component which captures camera images.

GearVRF DCO signed off by: Nola Donato nola.donato@samsung.com

Original PR: https://github.com/Samsung/GearVRf/pull/2010
SXR-DCO-1.0-Signed-off-by: Mihail Marinov <m.marinov@samsung.com>

### CODE REVIEW

**Comment by liaxim** [comment]
Compiles now, need to double-check the right changes were picked and then verify.

**Comment by liaxim** [comment]
Looks to match the original

**Comment by NolaDonato** [comment]
I have tested this with gvr-avatar, gvr-aravatar, gvr-meshanimation, gvr-morph.
I tried to test with gvr-javascript but this demo would not start due to not being able to find the script extension.

**Comment by liaxim** [comment]
gvr-javascript and specifically failing to dlopen libjav8.so is known issue. Xu is looking at it.

**Comment by liaxim** [comment]
sxr-avatar works. Can be merged.

**Pull request merged**
