### PR TITLE
Filter shadow maps

### PR DESCRIPTION
**Pull request by NolaDonato**
Add PCF filtering to shadow maps to improve edges

SXR DCO signed off by: Nola Donato nola.donato@samsung.com

Shadow test golden masters will be updated after this PR is merged

### CODE REVIEW

**Comment by liaxim** [comment]
Tried sxr-shadows on Note 9/Adreno 630: the balls and the box have no shadow at all. The feet's shadow appears and disappears in a weird way.

Turns out sxr-shadows doesn't work correctly with Daydream but it is not due to this change. Probably my recent Daydream PR is the cause. Will look into it.

**Comment by liaxim** [comment]
Note8, sxr-shadows: some of the shadows are missing, something is off along the border. Video attached:


[20190416_090811.mp4.zip](https://github.com/sxrsdk/sxrsdk/files/3085867/20190416_090811.mp4.zip)

**Comment by NolaDonato** [comment]
I tried this PR on my Note 8 running Android Pie and it did not show the artifacts you saw. What Android version does your Note 8 have?

**Comment by liaxim** [comment]
Will clean/rebuild and try on few different devices again.

**Comment by liaxim** [comment]
My Note8 info:

**Comment by NolaDonato** [comment]
I fixed this artifact

**Comment by liaxim** [comment]
pr
master

Couple of the shadows visible in master are no more. Also there is something with the brightness. I have to say master looks better to me. The big ball's shadow is kind off too.

**Comment by liaxim** [comment]
https://github.com/sxrsdk/sxrsdk-demos/pull/80 is needed too. sxr-shadows looks much better, still too bright for me.

**Pull request merged**
